title: "biblion"
description: "Logs inversés : lectures, notes, méthodes, ressources"
theme: minima

# Project site : https://oledeuff.github.io/biblion/
url: "https://oledeuff.github.io"
baseurl: "/biblion"

timezone: Europe/Paris
show_excerpts: true
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Menu de header (minima)
header_pages:
  - index.md
  - tags.md
  - archive.md
  - about.md

# Plugins autorisés GitHub Pages (optionnel, mais utile)
plugins:
  - jekyll-feed
